@extends('layouts.app', ['heading' => 'Ma caisse', 'eyebrow' => 'Espace opérateur'])
@section('content')
<div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="section-kicker">{{ auth()->user()->company->name }}</p><h2 class="hero-title">Ma caisse.</h2><p class="muted-copy">Votre session de travail et ses mouvements.</p></div><a class="button-secondary" href="{{ route('dashboard') }}">Tableau de bord</a></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(!$session)
<section class="panel max-w-2xl"><p class="section-kicker">Ouverture</p><h3 class="mb-2 text-xl font-bold">Aucune session de caisse ouverte</h3><p class="muted-copy mb-6">Choisissez une caisse active et saisissez le fond de caisse initial.</p>
@if(!auth()->user()->hasPermission('cash.open'))<p>Votre compte ne dispose pas du droit d’ouverture de caisse.</p>
@elseif($registers->isEmpty())<p>Aucune caisse active n’est disponible pour votre entreprise.</p>
@else
<form method="post" action="{{ route('cash.my-session.open') }}" class="space-y-4">@csrf
<label class="block text-sm font-semibold">Caisse<select class="search-input mt-2 w-full" name="cash_register_id" required>@foreach($registers as $register)<option value="{{ $register->id }}">{{ $register->name }}</option>@endforeach</select></label>
<label class="block text-sm font-semibold">Montant d’ouverture (FCFA)<input class="search-input mt-2 w-full" type="number" min="0" step="0.01" name="opening_amount" value="{{ old('opening_amount', '0.00') }}" required></label>
<input type="hidden" name="return_to" value="{{ request('return_to') === 'invoice' ? 'invoice' : '' }}">
<button class="button-primary">Ouvrir ma caisse</button></form>
@endif</section>
@else
<section class="panel mb-6"><div class="panel-heading"><div><p class="section-kicker">{{ $session->cashRegister->code }} · Ouverte le {{ $session->opened_at->format('d/m/Y à H:i') }}</p><h3>{{ $session->cashRegister->name }}</h3><p class="muted-copy">Session {{ $session->id }} · Ouverte par {{ $session->openedBy->name }}</p></div><span class="status-pill status-green">Ouverte</span></div>
<div class="stats-grid"><div class="stat-card"><p>Montant initial</p><strong>{{ \App\Support\CashAmount::format($snapshot['opening_amount']) }} <em>FCFA</em></strong></div><div class="stat-card accent-green"><p>Total entrées</p><strong>{{ \App\Support\CashAmount::format($snapshot['total_in']) }} <em>FCFA</em></strong></div><div class="stat-card accent-red"><p>Total sorties</p><strong>{{ \App\Support\CashAmount::format($snapshot['total_out']) }} <em>FCFA</em></strong></div><div class="stat-card accent-blue"><p>Solde théorique</p><strong>{{ \App\Support\CashAmount::format($snapshot['expected_amount']) }} <em>FCFA</em></strong></div></div>
<div class="mt-6 flex flex-wrap gap-3"><a class="button-primary" href="{{ route('invoices.create') }}">Nouvelle facture</a><a class="button-secondary" href="{{ route('cash-registers.show', $session->cashRegister) }}">Voir tous les détails</a></div></section>
@if(auth()->user()->hasPermission('cash.close'))<section id="close-cash" class="panel mb-6"><p class="section-kicker">Clôture de caisse</p><h3 class="mb-4 text-xl font-bold">Compter et clôturer</h3><p class="mb-4">Solde théorique : <strong>{{ \App\Support\CashAmount::format($snapshot['expected_amount']) }} FCFA</strong></p><form method="post" action="{{ route('cash-registers.sessions.close', [$session->cashRegister, $session]) }}" class="grid gap-4 md:grid-cols-2">@csrf<label class="block text-sm font-semibold">Montant réellement compté<input class="search-input mt-2 w-full" name="closing_amount" type="number" min="0" step="0.01" required></label><label class="block text-sm font-semibold">Observation (obligatoire en cas d’écart)<input class="search-input mt-2 w-full" name="closing_note" maxlength="2000"></label><div><button class="button-secondary">Clôturer ma caisse</button></div></form></section>@endif
<section class="panel"><div class="panel-heading"><div><p class="section-kicker">Historique</p><h3>Mouvements récents</h3></div><span>{{ $snapshot['movement_count'] }} mouvement(s)</span></div>
@if($movements->isEmpty())<p class="muted-copy">Aucun mouvement enregistré.</p>@else<div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Entrée</th><th>Sortie</th><th>Solde après mouvement</th><th>Opérateur</th></tr></thead><tbody>@foreach($movements as $movement)<tr><td>{{ $movement->occurred_at->format('d/m/Y H:i') }}</td><td>{{ $movement->type }}</td><td>{{ $movement->description ?: '—' }}</td><td>{{ $movement->direction === 'in' ? \App\Support\CashAmount::format($movement->amount).' FCFA' : '—' }}</td><td>{{ $movement->direction === 'out' ? \App\Support\CashAmount::format($movement->amount).' FCFA' : '—' }}</td><td>{{ \App\Support\CashAmount::format((string)$movement->balance_after).' FCFA' }}</td><td>{{ $movement->createdBy?->name ?: '—' }}</td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $movements->links() }}</div>@endif</section>
@endif
@endsection
