@extends('layouts.app', ['heading' => 'Encaissements', 'eyebrow' => 'Opérations financières'])
@section('content')
<div class="mb-8"><p class="section-kicker">Caisse & banque</p><h2 class="hero-title">Chaque encaissement compte.</h2><p class="muted-copy">Historique des paiements enregistrés pour votre entreprise.</p></div>
<section class="panel">
    <div class="panel-heading"><div><p class="section-kicker">Journal</p><h3>Paiements récents</h3></div><strong>{{ number_format($payments->getCollection()->where('status', 'posted')->sum(fn ($payment) => (float) $payment->amount), 2, ',', ' ') }} FCFA sur cette page</strong></div>
    @if($payments->isEmpty())<div class="empty-state"><span>↗</span><p>Aucun paiement enregistré</p><small>Les encaissements apparaîtront ici.</small></div>
    @else<div class="table-wrap"><table class="data-table"><thead><tr><th>N° paiement / reçu</th><th>Facture</th><th>Client</th><th>Date</th><th>Mode</th><th>Référence</th><th>Montant</th><th>Opérateur</th><th>Statut</th><th></th></tr></thead><tbody>@foreach($payments as $payment)<tr><td>{{ $payment->number }}<small class="block text-slate-500">{{ $payment->receipt_number ?: 'Reçu à numéroter' }}</small></td><td><a class="font-semibold text-[#28745d]" href="{{ route('invoices.show', $payment->invoice) }}">{{ $payment->invoice->number }}</a></td><td>{{ $payment->customer->legal_name ?: trim($payment->customer->first_name.' '.$payment->customer->last_name) }}</td><td>{{ $payment->paid_at->format('d/m/Y') }}</td><td>{{ $payment->paymentMethod->name }}</td><td>{{ $payment->reference ?: '—' }}</td><td>{{ number_format($payment->amount, 2, ',', ' ') }} FCFA</td><td>{{ $payment->receivedBy?->name ?? 'Compte supprimé' }}</td><td>{{ $payment->status === 'posted' ? 'Enregistré' : ucfirst($payment->status) }}</td><td><a class="button-secondary" href="{{ route('payments.receipt', $payment) }}">Voir le reçu</a></td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $payments->links() }}</div>@endif
</section>
@endsection
