@extends('layouts.app', ['heading' => 'Reçu de paiement', 'eyebrow' => $payment->company->name])
@section('content')
<div class="mb-5 flex justify-end gap-2 print:hidden"><a class="button-secondary" href="{{ route('payments.index') }}">Retour aux encaissements</a><button class="button-primary" onclick="window.print()" type="button">Imprimer le reçu</button></div>
<article class="panel mx-auto max-w-3xl p-8 print-receipt">
    <header class="flex items-start justify-between gap-6 border-b pb-6"><div><p class="section-kicker">{{ $payment->company->name }}</p><h1 class="text-3xl font-bold text-[#173b36]">Reçu de paiement</h1>@if($payment->company->legal_name)<p>{{ $payment->company->legal_name }}</p>@endif<p>{{ $payment->company->email }} @if($payment->company->phone)· {{ $payment->company->phone }}@endif</p></div><div class="text-right"><p class="section-kicker">N° du reçu</p><strong class="text-xl">{{ $payment->receipt_number }}</strong><p>{{ $payment->paid_at->format('d/m/Y') }}</p></div></header>
    <section class="grid gap-6 border-b py-6 sm:grid-cols-2"><div><p class="section-kicker">Reçu de</p><strong>{{ $payment->customer->legal_name ?: trim($payment->customer->first_name.' '.$payment->customer->last_name) }}</strong><p>{{ $payment->customer->email }}</p><p>{{ $payment->customer->phone }}</p></div><div><p class="section-kicker">Facture concernée</p><a class="font-semibold text-[#28745d] print:text-black" href="{{ route('invoices.show', $payment->invoice) }}">{{ $payment->invoice->number }}</a><p>Émise le {{ $payment->invoice->issue_date->format('d/m/Y') }}</p></div></section>
    <dl class="space-y-4 py-6"><div class="flex justify-between gap-4"><dt>Montant réglé</dt><dd class="text-2xl font-bold">{{ number_format($payment->amount, 2, ',', ' ') }} FCFA</dd></div><div class="flex justify-between gap-4"><dt>Mode de paiement</dt><dd>{{ $payment->paymentMethod->name }}</dd></div><div class="flex justify-between gap-4"><dt>Référence</dt><dd>{{ $payment->reference ?: '—' }}</dd></div><div class="flex justify-between gap-4 border-t pt-4"><dt>Solde restant après paiement</dt><dd class="font-semibold">{{ number_format($payment->balance_after ?? $payment->invoice->balance_due, 2, ',', ' ') }} FCFA</dd></div></dl>
    <footer class="border-t pt-5 text-sm text-slate-600"><p>Enregistré par : {{ $payment->receivedBy?->name ?? 'Compte supprimé' }}</p><p class="mt-5">Ce reçu confirme l’encaissement du montant indiqué pour la facture référencée ci-dessus.</p></footer>
</article>
<style>@media print { body { background: white !important; } nav, aside, header.site-header, .print\:hidden { display: none !important; } main { padding: 0 !important; } .print-receipt { max-width: 100% !important; border: 0 !important; box-shadow: none !important; margin: 0 !important; } }</style>
@endsection
