@extends('layouts.app', ['heading' => 'Nouvelle facture', 'eyebrow' => 'Espace opérateur · Facturation'])
@section('content')
<div class="mb-6 flex items-end justify-between"><div><p class="section-kicker">Facturation rapide</p><h2 class="hero-title">Nouvelle facture.</h2><p class="muted-copy">Recherchez un client, ajoutez les articles et enregistrez le paiement si besoin.</p></div><a class="button-secondary" href="{{ route('invoices.index') }}">Retour aux factures</a></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@if($errors->has('cash_session_id') && auth()->user()->hasPermission('cash.open'))<a class="mt-3 inline-block font-bold underline" href="{{ route('cash.my-session', ['return_to' => 'invoice']) }}">Ouvrir ma caisse puis revenir</a>@endif</div>@endif
<form id="operator-invoice-form" method="post" action="{{ route('invoices.store') }}" class="space-y-6">@csrf<input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', $idempotencyKey) }}">
<section class="panel"><p class="section-kicker">Client</p><label for="customer-search" class="mb-2 block font-semibold">Rechercher un client</label><div class="relative"><input id="customer-search" class="search-input w-full" type="search" placeholder="Nom, téléphone, email ou référence..." autocomplete="off"><input id="customer_id" type="hidden" name="customer_id" value="{{ old('customer_id', $draft['customer_id'] ?? '') }}"><div id="customer-results" class="absolute z-20 mt-1 hidden max-h-72 w-full overflow-y-auto rounded-lg border bg-white shadow-xl" role="listbox"></div></div><div id="selected-customer" class="mt-3 rounded-lg bg-emerald-50 p-3 text-emerald-900 {{ $selectedCustomer ? '' : 'hidden' }}">Client sélectionné : <strong id="selected-customer-name">{{ $selectedCustomer?->legal_name ?: trim(($selectedCustomer?->first_name ?? '').' '.($selectedCustomer?->last_name ?? '')) }}</strong><button type="button" id="clear-customer" class="ml-3 underline">Changer</button></div><p id="customer-empty" class="mt-3 hidden text-sm text-slate-600">Aucun client correspondant.</p>
@if(auth()->user()->hasPermission('customer.create'))<button id="quick-customer-toggle" type="button" class="mt-3 text-sm font-bold text-emerald-800 underline">+ Créer un client rapidement</button><div id="quick-customer-panel" class="mt-4 hidden rounded-lg bg-slate-50 p-4"><div class="grid gap-3 md:grid-cols-2"><label class="text-sm font-semibold">Type<select id="quick-type" class="search-input mt-1 w-full"><option value="individual">Particulier</option><option value="company">Entreprise</option></select></label><label id="quick-legal-wrap" class="hidden text-sm font-semibold">Raison sociale<input id="quick-legal" class="search-input mt-1 w-full"></label><label id="quick-first-wrap" class="text-sm font-semibold">Prénom<input id="quick-first" class="search-input mt-1 w-full"></label><label id="quick-last-wrap" class="text-sm font-semibold">Nom<input id="quick-last" class="search-input mt-1 w-full"></label><label class="text-sm font-semibold">Téléphone<input id="quick-phone" class="search-input mt-1 w-full"></label><label class="text-sm font-semibold">Email<input id="quick-email" class="search-input mt-1 w-full" type="email"></label></div><p id="quick-customer-error" class="mt-2 hidden text-sm text-red-700"></p><button id="quick-customer-submit" type="button" class="button-primary mt-3">Créer et sélectionner</button></div>@endif
@error('customer_id')<span class="mt-2 block text-sm text-red-700">{{ $message }}</span>@enderror</section>
<section class="panel"><div class="panel-heading"><div><p class="section-kicker">Articles</p><h3>Produits et services</h3></div></div><label for="product-search" class="mb-2 block font-semibold">Rechercher un produit ou service</label><div class="relative"><input id="product-search" class="search-input w-full" type="search" placeholder="Nom ou référence..." autocomplete="off"><div id="product-results" class="absolute z-20 mt-1 hidden max-h-64 w-full overflow-y-auto rounded-lg border bg-white shadow-xl" role="listbox"></div></div><p id="product-empty" class="mt-2 hidden text-sm text-slate-600">Aucun article trouvé.</p><div id="invoice-lines" class="mt-5 space-y-3"></div>@error('lines')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror
<div class="ml-auto mt-6 max-w-sm space-y-2 border-t pt-4"><div class="flex justify-between"><span>Sous-total</span><strong id="subtotal-label">0 FCFA</strong></div><div class="flex justify-between"><span>Remises</span><strong id="discount-label">0 FCFA</strong></div><div class="flex justify-between"><span>Taxes</span><strong id="tax-label">0 FCFA</strong></div><div class="flex justify-between border-t pt-2 text-lg"><span>Total TTC</span><strong id="total-label">0 FCFA</strong></div></div></section>
<section class="panel"><div class="grid gap-4 md:grid-cols-2"><label class="block text-sm font-semibold">Date d’émission<input class="search-input mt-2 w-full" type="date" name="issue_date" value="{{ old('issue_date', $draft['issue_date'] ?? now()->toDateString()) }}" required></label><label class="block text-sm font-semibold">Échéance<input class="search-input mt-2 w-full" type="date" name="due_date" value="{{ old('due_date', $draft['due_date'] ?? '') }}"></label></div><label class="mt-4 block text-sm font-semibold">Notes<textarea class="search-input mt-2 w-full" name="notes" rows="2">{{ old('notes', $draft['notes'] ?? '') }}</textarea></label></section>
<section class="panel {{ $paymentMethods->isEmpty() ? 'hidden' : '' }}"><p class="section-kicker">Encaissement</p><label class="mb-3 flex items-center gap-2 font-semibold"><input id="take-payment" type="checkbox" {{ old('payment_method_id', $draft['payment_method_id'] ?? '') ? 'checked' : '' }}> Enregistrer un paiement maintenant</label><div id="payment-fields" class="{{ old('payment_method_id', $draft['payment_method_id'] ?? '') ? '' : 'hidden' }} grid gap-4 md:grid-cols-2"><label class="block text-sm font-semibold">Mode de paiement<select id="payment_method_id" name="payment_method_id" class="search-input mt-2 w-full"><option value="">Choisir</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" data-code="{{ $method->code }}" @selected(old('payment_method_id', $draft['payment_method_id'] ?? '') === $method->id)>{{ $method->name }}</option>@endforeach</select></label><label class="block text-sm font-semibold">Montant reçu (FCFA)<input id="payment_amount" class="search-input mt-2 w-full" name="payment_amount" type="number" min="0.01" step="0.01" value="{{ old('payment_amount', $draft['payment_amount'] ?? '') }}"></label><label id="bank-account-info" class="hidden block text-sm font-semibold md:col-span-2">Compte bancaire destinataire<select id="bank_account_id" name="bank_account_id" class="search-input mt-2 w-full"><option value="">Choisir un compte</option>@foreach($bankAccounts as $account)<option value="{{ $account->id }}" @selected(old('bank_account_id', $draft['bank_account_id'] ?? '') === $account->id)>{{ $account->name }} · {{ $account->bank_name }}</option>@endforeach</select>@error('bank_account_id')<span class="block text-sm text-red-700">{{ $message }}</span>@enderror</label><div id="cash-session-info" class="hidden rounded-lg bg-emerald-50 p-3 text-emerald-900 md:col-span-2">@if($myOpenSession)Caisse utilisée : <strong>{{ $myOpenSession->cashRegister->name }}</strong> · session ouverte le {{ $myOpenSession->opened_at->format('d/m/Y H:i') }}@else<span class="text-amber-900">Aucune session de caisse ouverte.</span> @if(auth()->user()->hasPermission('cash.open'))<a class="font-bold underline" href="{{ route('cash.my-session', ['return_to'=>'invoice']) }}">Ouvrir ma caisse</a>@endif @endif</div><label class="block text-sm font-semibold">Référence<input class="search-input mt-2 w-full" name="payment_reference" value="{{ old('payment_reference', $draft['payment_reference'] ?? '') }}"></label><label class="block text-sm font-semibold">Date de paiement<input class="search-input mt-2 w-full" type="date" name="payment_date" value="{{ old('payment_date', $draft['payment_date'] ?? now()->toDateString()) }}"></label></div></section>
<div class="flex flex-wrap justify-end gap-3">@if(!$myOpenSession && auth()->user()->hasPermission('cash.open'))<button type="submit" formmethod="post" formaction="{{ route('cash.my-session.prepare') }}" class="button-secondary">Ouvrir ma caisse</button>@endif<a class="button-secondary" href="{{ route('invoices.index') }}">Annuler</a><button class="button-primary">Enregistrer la facture</button></div>
</form>
<script>
(() => {
    const form = document.getElementById('operator-invoice-form');
    const csrf = form.querySelector('input[name="_token"]').value;
    const customerSearch = document.getElementById('customer-search');
    const customerId = document.getElementById('customer_id');
    const customerResults = document.getElementById('customer-results');
    const customerEmpty = document.getElementById('customer-empty');
    const selectedCustomer = document.getElementById('selected-customer');
    const customerName = document.getElementById('selected-customer-name');
    const productSearch = document.getElementById('product-search');
    const productResults = document.getElementById('product-results');
    const productEmpty = document.getElementById('product-empty');
    const lines = document.getElementById('invoice-lines');
    let customerTimer;
    let productTimer;
    let customerController;
    let productController;
    const formatMoney = value => `${new Intl.NumberFormat('fr-FR', {maximumFractionDigits: 2}).format(value)} FCFA`;
    const draftLines = @json(old('lines', $draft['lines'] ?? []));
    const savedProducts = @json($draftProducts);
    const selected = new Map(savedProducts.map(product => [product.id, product]));
    const setCustomer = customer => { customerId.value = customer.id; customerName.textContent = customer.name; selectedCustomer.classList.remove('hidden'); customerResults.classList.add('hidden'); customerEmpty.classList.add('hidden'); customerSearch.value = customer.name; };
    const renderCustomers = data => { customerResults.replaceChildren(); data.forEach(customer => { const button = document.createElement('button'); button.type='button'; button.className='block w-full border-b p-3 text-left hover:bg-emerald-50'; button.innerHTML=`<strong></strong><small class="block text-slate-600"></small>`; button.querySelector('strong').textContent=customer.name; button.querySelector('small').textContent=[customer.phone,customer.email].filter(Boolean).join(' · '); button.addEventListener('click',()=>setCustomer(customer)); customerResults.append(button); }); customerResults.classList.toggle('hidden', data.length===0); customerEmpty.classList.toggle('hidden', data.length!==0); };
    customerSearch.addEventListener('input',()=>{ clearTimeout(customerTimer); if(customerController) customerController.abort(); const q=customerSearch.value.trim(); customerId.value=''; selectedCustomer.classList.add('hidden'); if(q.length<2){customerResults.classList.add('hidden');customerEmpty.classList.add('hidden');return;} customerTimer=setTimeout(async()=>{customerController=new AbortController();try{const response=await fetch(`{{ route('customers.search') }}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'},signal:customerController.signal});const json=await response.json();renderCustomers(json.data||[]);}catch(error){if(error.name!=='AbortError') customerEmpty.classList.remove('hidden');}},250);});
    document.getElementById('clear-customer')?.addEventListener('click',()=>{customerId.value='';customerSearch.value='';selectedCustomer.classList.add('hidden');customerSearch.focus();});
    document.getElementById('quick-customer-toggle')?.addEventListener('click',()=>document.getElementById('quick-customer-panel').classList.toggle('hidden'));
    document.getElementById('quick-type')?.addEventListener('change',event=>{const company=event.target.value!=='individual';document.getElementById('quick-legal-wrap').classList.toggle('hidden',!company);document.getElementById('quick-first-wrap').classList.toggle('hidden',company);document.getElementById('quick-last-wrap').classList.toggle('hidden',company);});
    document.getElementById('quick-customer-submit')?.addEventListener('click',async()=>{const error=document.getElementById('quick-customer-error');error.classList.add('hidden');const type=document.getElementById('quick-type').value;const body={type,legal_name:document.getElementById('quick-legal').value,first_name:document.getElementById('quick-first').value,last_name:document.getElementById('quick-last').value,phone:document.getElementById('quick-phone').value,email:document.getElementById('quick-email').value};try{const response=await fetch(`{{ route('customers.quick-store') }}`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(Object.values(json.errors||{}).flat().join(' ' )||'Création impossible.');setCustomer(json.data);document.getElementById('quick-customer-panel').classList.add('hidden');}catch(exception){error.textContent=exception.message;error.classList.remove('hidden');}});
    const addLine = (product, line = {}) => {if(selected.has(product.id))return;selected.set(product.id,product);const index=lines.children.length;const row=document.createElement('div');row.className='grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_110px_130px_130px_150px] md:items-center';row.dataset.productId=product.id;row.dataset.price=product.price;row.dataset.tax=product.tax_rate;row.innerHTML=`<div><strong class="product-name"></strong><small class="block text-slate-500"></small><input type="hidden" name="lines[${index}][product_id]" value="${product.id}"><input class="line-quantity" type="hidden" name="lines[${index}][quantity]" value="${line.quantity||'1.000'}"><input class="line-discount" type="hidden" name="lines[${index}][discount_amount]" value="${line.discount_amount||'0.00'}"></div><label class="text-sm">Quantité<input class="search-input line-quantity-visible mt-1 w-full" type="number" min="0.001" step="0.001" value="${line.quantity||'1.000'}"></label><label class="text-sm">Remise<input class="search-input line-discount-visible mt-1 w-full" type="number" min="0" step="0.01" value="${line.discount_amount||'0.00'}"></label><div class="text-sm">Prix unitaire<strong class="block"></strong></div><div class="flex items-center justify-between text-sm"><span>Total ligne<strong class="line-total block"></strong></span><button type="button" class="remove-line text-red-700">Retirer</button></div>`;row.querySelector('.product-name').textContent=product.name;row.querySelector('small').textContent=product.description||'';row.querySelectorAll('strong')[1].textContent=formatMoney(Number(product.price));row.querySelector('.line-quantity-visible').addEventListener('input',event=>{row.querySelector('.line-quantity').value=event.target.value;updateTotals();});row.querySelector('.line-discount-visible').addEventListener('input',event=>{row.querySelector('.line-discount').value=event.target.value;updateTotals();});row.querySelector('.remove-line').addEventListener('click',()=>{selected.delete(product.id);row.remove();reindexLines();updateTotals();});lines.append(row);updateTotals();};
    const reindexLines=()=>[...lines.children].forEach((row,index)=>{row.querySelector('input[type=hidden]').name=`lines[${index}][product_id]`;row.querySelector('.line-quantity').name=`lines[${index}][quantity]`;row.querySelector('.line-discount').name=`lines[${index}][discount_amount]`;});
    const updateTotals=()=>{let subtotal=0,discountTotal=0,tax=0;[...lines.children].forEach(row=>{const base=Number(row.dataset.price)*Number(row.querySelector('.line-quantity').value||0);const discount=Number(row.querySelector('.line-discount').value||0);const taxable=Math.max(0,base-discount);const taxAmount=taxable*Number(row.dataset.tax)/100;subtotal+=base;discountTotal+=discount;tax+=taxAmount;row.querySelector('.line-total').textContent=formatMoney(taxable+taxAmount);});document.getElementById('subtotal-label').textContent=formatMoney(subtotal);document.getElementById('discount-label').textContent=formatMoney(discountTotal);document.getElementById('tax-label').textContent=formatMoney(tax);document.getElementById('total-label').textContent=formatMoney(subtotal-discountTotal+tax);};
    const renderProducts=data=>{productResults.replaceChildren();data.forEach(product=>{const button=document.createElement('button');button.type='button';button.className='block w-full border-b p-3 text-left hover:bg-emerald-50';button.innerHTML='<strong></strong><small class="block text-slate-600"></small>';button.querySelector('strong').textContent=product.name;button.querySelector('small').textContent=`${formatMoney(Number(product.price))} · TVA ${product.tax_rate}%`;button.addEventListener('click',()=>{addLine(product);productSearch.value='';productResults.classList.add('hidden');});productResults.append(button);});productResults.classList.toggle('hidden',data.length===0);productEmpty.classList.toggle('hidden',data.length!==0);};
    productSearch.addEventListener('input',()=>{clearTimeout(productTimer);if(productController)productController.abort();const q=productSearch.value.trim();if(q.length<2){productResults.classList.add('hidden');productEmpty.classList.add('hidden');return;}productTimer=setTimeout(async()=>{productController=new AbortController();try{const response=await fetch(`{{ route('products.search') }}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'},signal:productController.signal});const json=await response.json();renderProducts(json.data||[]);}catch(error){if(error.name!=='AbortError')productEmpty.classList.remove('hidden');}},250);});
    draftLines.forEach(line=>{const product=selected.get(line.product_id);if(product)addLine(product,line);});
    document.getElementById('take-payment')?.addEventListener('change',event=>document.getElementById('payment-fields').classList.toggle('hidden',!event.target.checked));
    const paymentMethod=document.getElementById('payment_method_id');const cashInfo=document.getElementById('cash-session-info');const bankInfo=document.getElementById('bank-account-info');const bankSelect=document.getElementById('bank_account_id');const togglePaymentAccount=()=>{const isCash=paymentMethod?.selectedOptions[0]?.dataset.code==='cash';cashInfo.classList.toggle('hidden',!isCash);bankInfo.classList.toggle('hidden',isCash||!bankSelect||bankSelect.options.length<2);if(bankSelect)bankSelect.required=!isCash&&bankSelect.options.length>1;};paymentMethod?.addEventListener('change',togglePaymentAccount);if(paymentMethod?.value)togglePaymentAccount();
    form.addEventListener('submit',event=>{if(!customerId.value){event.preventDefault();customerSearch.focus();alert('Sélectionnez un client dans les résultats.');}else if(lines.children.length===0){event.preventDefault();productSearch.focus();alert('Ajoutez au moins un produit ou service.');}});
})();
</script>
@endsection
