@extends('layouts.app', ['heading' => 'Facturation', 'eyebrow' => 'Opérations financières'])
@section('content')
<div class="mb-8"><p class="section-kicker">Ventes</p><h2 class="hero-title">La facturation, sans angle mort.</h2><p class="muted-copy">Suivez les émissions, les échéances et les soldes dus.</p></div>
<section class="panel">
    <form method="get" class="toolbar"><input name="search" value="{{ request('search') }}" class="search-input" placeholder="Rechercher une facture…"><select name="status" class="search-input"><option value="">Tous les statuts</option>@foreach(['draft', 'sent', 'accepted', 'rejected', 'expired', 'cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select><button class="button-secondary">Filtrer</button></form>
    @if($invoices->isEmpty())<div class="empty-state"><span>▤</span><p>Aucune facture enregistrée</p><small>Les factures converties depuis un devis apparaîtront ici.</small></div>
    @else<div class="table-wrap"><table class="data-table"><thead><tr><th>Numéro</th><th>Client</th><th>Date</th><th>Total</th><th>Payé</th><th>Solde</th><th>Statut commercial</th><th>Statut financier</th><th></th></tr></thead><tbody>@foreach($invoices as $invoice)<tr><td><a class="font-semibold text-[#28745d]" href="{{ route('invoices.show', $invoice) }}">{{ $invoice->number }}</a></td><td>{{ $invoice->customer->legal_name ?: trim($invoice->customer->first_name.' '.$invoice->customer->last_name) }}</td><td>{{ $invoice->issue_date->format('d/m/Y') }}</td><td>{{ number_format($invoice->total, 2, ',', ' ') }} FCFA</td><td>{{ number_format($invoice->amount_paid, 2, ',', ' ') }} FCFA</td><td>{{ number_format($invoice->balance_due, 2, ',', ' ') }} FCFA</td><td><span class="status-pill status-neutral">{{ ucfirst($invoice->status) }}</span></td><td>{{ $invoice->financialStatusLabel() }}@if($invoice->daysOverdue() > 0)<small class="block text-red-700">Échue · {{ $invoice->daysOverdue() }} j</small>@endif</td><td><a class="button-secondary" href="{{ route('invoices.show', $invoice) }}">Consulter</a></td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $invoices->links() }}</div>@endif
</section>
@endsection
